FROM ubuntu:latest #this is a comment
MAINTAINER Your name "you@example.com" # comment

ENV VAR1=1234 VAR2=234 VAR3="a string" VAR4="please parse me too"

ENV VAR="this is a string" dfgdfgdfg--unparsed errors
# comment

ENV V1=1 V2=222

ENV DEBIAN_FRONTEND noninteractive
#

ENV GHI="data spaces" JKL="uck"   # comment

LABEL "asdasd#asdasd" = "asdasd#asdasd"  # fix comment in string

ENV VAR AAAA \
        BBBB \
        BBCC
LABEL 'aaa\
sdf" = "sdfsdf"' = sdfsdf

