FROM abcdddfg\
a\\\\\\\
b \# not-comment # comment
#comment
MAINTAINER Graham Bevan "email!
hgdhgf

ENV DEBIAN_FRONTEND noninteractive # commentZZ
ENV LANG=C
ENV LC_ALL=C
ENV ABC=123 DEF=567
ENV GHI="data spaces" JKL="uck"   # commentx


"quoted
multiline
until end quote " # out of context, so error


ENV VAR1 val1\
    val2 \

"quoted"

RUN \
    apt-get -yq update && \
    apt-get dist-upgrade -yq && \
    apt-get install -yqq wget aptitude htop vim vim-puppet git traceroute dnsutils \
      curl ssh sudo psmisc gcc make build-essential libfreetype6 libfontconfig \
      augeas-tools tree tcpdump && \
    mkdir /var/run/sshd && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config && \
    useradd --create-home -s /bin/bash mean && \
    su - mean -c "mkdir -p .ssh; chmod 700 .ssh" && \
    echo -n "mean:`openssl rand -base64 15`" | chpasswd && \
    su - mean -c "touch .hushlogin" && \
    mkdir -p /etc/sudoers.d && \
    echo "mean ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/mean && \
    chmod 0440 /etc/sudoers.d/mean && \
    echo "set modeline" > /etc/vim/vimrc.local && \
    echo "export TERM=vt100\nexport LANG=C\nexport LC_ALL=C" > /etc/profile.d/dockenv.sh && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN cat /etc/passwdx

LABEL "aaa" = "bbb"
LABEL "aaa\
bbb" = 'ccc\
ddd'
LABEL
